version: '3'

services:
  postgres:
    image: mdillon/postgis
    restart: always
    container_name: fourSaveDB
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
